services:
  - type: web
    name: marketo-ssfs-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MARKETO_API_KEY
        sync: false
      - key: MARKETO_PROVIDER_NAME
        value: Marketo SSFS Lead Scoring Calculator
      - key: MARKETO_SUPPORT_CONTACT
        sync: false
      - key: MARKETO_MUNCHKIN_ID
        sync: false
      - key: SERVER_URL
        sync: false
